package constants

const (
	LOGIN_KEY = "LOGIN"
	PASSWORD_KEY = "PASSW"

	LOGIN_ERROR = "ERROR NO_LOGIN"
	PASSWORD_ERROR = "ERROR NO_PASSWORD"
	ARGUMENTS_NUMBER_ERROR = "ERROR ARGUMENTS_NUMBER"
	WRONG_LOGIN_OR_PASSWORD_ERROR = "ERROR LOGIN_OR_PASSWORD"
	UNKNOWN_COMMAND_ERROR = "ERROR UNKNOWN_COMMAND"

	SUCCESS_AUTH = "SUCC AUTH"

	ROOM = "ROOM"
	NEW = "NEW"
	GAME_ID_KEY = "GAME_ID"
)
