package constants

const (
	LOGIN_KEY = "LOGIN"
	PASSWORD_KEY = "PASSW"

	LOGIN_ERROR = "ERROR NO_LOGIN"
	PASSWORD_ERROR = "ERROR NO_PASSWORD"
	ARGUMENTS_NUMBER_ERROR = "ERROR ARGUMENTS_NUMBER"
	WRONG_LOGIN_OR_PASSWORD_ERROR = "ERROR LOGIN_OR_PASSWORD"
	UNKNOWN_COMMAND_ERROR = "ERROR UNKNOWN_COMMAND"
	INCORRECT_MOVE_ERROR = "ERROR INCORRECT_MOVE"
	INCORRECT_ROOM_ID_ERROR = "ERROR INCORRECT_ROOM_ID"
	NON_UNIQUE_LOGIN_ERROR = "ERROR NON_UNIQUE_LOGIN"
	NOT_YOUR_TURN_ERROR = "ERROR NOT_YOUR_TURN"

	SUCCESS_AUTH = "SUCC AUTH"
	SUCCESS_REG = "SUCC REG"
	SUCCESS_ROOM = "SUCC ROOM"

	ROOM = "ROOM"
	NEW = "NEW"
	GAME_ID_KEY = "GAME_ID"
	MOVE_KEY = "MOVE"
	REG_KEY = "REG"
)
